v_db_import_path = "D:\ISE\ARBUTUS PROJECTS\CBG\CBG_ERECON\data\files"
v_data_path = "D:\ISE\ARBUTUS PROJECTS\CBG\CBG_ERECON\FILES\DATA"
v_utils_path =  "D:\ISE\ARBUTUS PROJECTS\CBG\CBG_ERECON\zUTILS"

v_dclr_data_path = "D:\ISE\ARBUTUS PROJECTS\CBG\CBG_ERECON\FILES\DCLR\data"
v_dclr_processing_path =  "D:\ISE\ARBUTUS PROJECTS\CBG\CBG_ERECON\FILES\DCLR\zProcessing"
v_dclr_results_path =  "D:\ISE\ARBUTUS PROJECTS\CBG\CBG_ERECON\FILES\DCLR\Results"


